//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanySampleDataImporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTS_EMPLOYEES
    {
        public int EmployeeId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
